#pragma once

#include <string>
#include <vector>
#include <map>
#include <memory>
#include <nlohmann/json.hpp>
#include "cmdsdk/CommandMetadata.hpp"
#include "cmdsdk/OpenApiGenerator.hpp"

namespace cmdsdk {

/**
 * OpenApiAggregator
 *
 * Merges multiple OpenAPI specifications from plugins into a single combined
 * OpenAPI document. Handles:
 *   - Path aggregation (all /api/{command} endpoints)
 *   - Component schema merging (all schemas in components.schemas)
 *   - Tag merging (group by plugin)
 *   - Conflict detection (optional)
 *
 * Can use either:
 *   1. Explicit plugin-provided OpenAPI specs (YAML/JSON)
 *   2. Auto-generated specs from CommandMetadata
 */
class OpenApiAggregator {
 public:
  struct PluginSpec {
    std::string plugin_name;
    std::string source;  // "auto-generated" or "file:path/to/spec.yml"
    nlohmann::json spec;
  };

  OpenApiAggregator() = default;

  /**
   * Add an auto-generated spec from CommandMetadata.
   *
   * Automatically creates OpenAPI path and component schemas from metadata.
   *
   * @param metadata CommandMetadata for command
   * @param plugin_name Plugin name (for tagging)
   */
  void addAutoGeneratedSpec(const CommandMetadata& metadata,
                            const std::string& plugin_name);

  /**
   * Add a pre-generated OpenAPI spec (from file or embedded).
   *
   * Used when plugin provides explicit openapi.spec.yml or similar.
   *
   * @param plugin_name Plugin name
   * @param spec OpenAPI 3.x spec object
   * @param source Optional source description (e.g., "file:openapi.spec.yml")
   */
  void addPluginSpec(const std::string& plugin_name,
                     const nlohmann::json& spec,
                     const std::string& source = "");

  /**
   * Build combined OpenAPI document.
   *
   * Merges all registered specs into a single OpenAPI 3.0 document with:
   *   - All paths from all plugins
   *   - All components.schemas merged
   *   - Tags organized by plugin
   *   - Proper versioning and info
   *
   * @param server_title Title for the API (e.g., "FastMCP Server")
   * @param server_version Version string (e.g., "0.1.0")
   * @return Complete OpenAPI 3.0 document
   */
  nlohmann::json buildCombinedSpec(const std::string& server_title = "FastMCP API",
                                    const std::string& server_version = "0.1.0");

  /**
   * Get individual plugin spec.
   *
   * @param plugin_name Plugin to retrieve
   * @return OpenAPI spec for that plugin, or empty object if not found
   */
  nlohmann::json getPluginSpec(const std::string& plugin_name) const;

  /**
   * List all registered plugins.
   *
   * @return Vector of plugin names
   */
  std::vector<std::string> listPlugins() const;

  /**
   * Clear all registered specs.
   */
  void clear();

 private:
  std::vector<PluginSpec> specs_;

  nlohmann::json mergeSchemas(const nlohmann::json& target_schemas,
                               const nlohmann::json& source_schemas);
};

// ============================================================================
// INLINE IMPLEMENTATIONS
// ============================================================================

inline void OpenApiAggregator::addAutoGeneratedSpec(
    const CommandMetadata& metadata,
    const std::string& plugin_name) {
  PluginSpec ps;
  ps.plugin_name = plugin_name;
  ps.source = "auto-generated";

  // Create minimal spec for this command
  std::string path = "/api/" + metadata.cmd_name;
  nlohmann::json path_item =
      OpenApiGenerator::commandMetadataToOpenApiPathItem(metadata, plugin_name);

  ps.spec["paths"][path] = path_item;

  // Add tag definition
  ps.spec["tags"] = nlohmann::json::array();
  ps.spec["tags"].push_back({
      {"name", plugin_name},
      {"description", "Commands from " + plugin_name + " plugin"}
  });

  specs_.push_back(ps);
}

inline void OpenApiAggregator::addPluginSpec(const std::string& plugin_name,
                                             const nlohmann::json& spec,
                                             const std::string& source) {
  PluginSpec ps;
  ps.plugin_name = plugin_name;
  ps.source = source.empty() ? plugin_name : source;
  ps.spec = spec;
  specs_.push_back(ps);
}

inline std::vector<std::string> OpenApiAggregator::listPlugins() const {
  std::vector<std::string> plugins;
  for (const auto& ps : specs_) {
    plugins.push_back(ps.plugin_name);
  }
  return plugins;
}

inline void OpenApiAggregator::clear() { specs_.clear(); }

inline nlohmann::json OpenApiAggregator::getPluginSpec(
    const std::string& plugin_name) const {
  for (const auto& ps : specs_) {
    if (ps.plugin_name == plugin_name) {
      return ps.spec;
    }
  }
  return nlohmann::json::object();
}

inline nlohmann::json OpenApiAggregator::mergeSchemas(
    const nlohmann::json& target_schemas,
    const nlohmann::json& source_schemas) {
  nlohmann::json result = target_schemas;
  if (source_schemas.is_object()) {
    for (auto it = source_schemas.begin(); it != source_schemas.end(); ++it) {
      result[it.key()] = it.value();
    }
  }
  return result;
}

inline nlohmann::json OpenApiAggregator::buildCombinedSpec(
    const std::string& server_title,
    const std::string& server_version) {
  nlohmann::json combined = nlohmann::json::object();

  // OpenAPI version and info
  combined["openapi"] = "3.0.0";
  combined["info"] = OpenApiGenerator::createOpenApiInfo(
      server_title, server_version,
      "Combined API from all registered plugins");
  combined["servers"] = nlohmann::json::array();
  combined["servers"].push_back({{"url", "/"}, {"description", "API Server"}});

  // Merge paths, components, and tags from all specs
  nlohmann::json all_paths = nlohmann::json::object();
  nlohmann::json all_schemas = nlohmann::json::object();
  nlohmann::json all_tags = nlohmann::json::array();
  std::map<std::string, bool> seen_tags;  // To avoid duplicate tags

  for (const auto& ps : specs_) {
    // Merge paths
    if (ps.spec.contains("paths") && ps.spec["paths"].is_object()) {
      for (auto it = ps.spec["paths"].begin(); it != ps.spec["paths"].end();
           ++it) {
        all_paths[it.key()] = it.value();
      }
    }

    // Merge component schemas
    if (ps.spec.contains("components") && ps.spec["components"].is_object() &&
        ps.spec["components"].contains("schemas")) {
      all_schemas = mergeSchemas(all_schemas, ps.spec["components"]["schemas"]);
    }

    // Collect tags (without duplicates)
    if (ps.spec.contains("tags") && ps.spec["tags"].is_array()) {
      for (const auto& tag : ps.spec["tags"]) {
        if (tag.is_object() && tag.contains("name")) {
          const std::string tag_name = tag["name"].get<std::string>();
          if (!seen_tags[tag_name]) {
            seen_tags[tag_name] = true;
            all_tags.push_back(tag);
          }
        }
      }
    }
  }

  combined["paths"] = all_paths;
  if (!all_schemas.empty()) {
    combined["components"]["schemas"] = all_schemas;
  }
  combined["tags"] = all_tags;

  return combined;
}

}  // namespace cmdsdk
